CREATE TABLE IF NOT EXISTS public.users (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200) NOT NULL,
    email varchar(200) NOT NULL,
    password varchar(200) NOT NULL,
    avatar varchar(100) NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NULL,
    deleted_at timestamp NULL,
    PRIMARY KEY(id)
)